### ISSUE TITLE
请问博主bbc的源是要英国ip吗

### ISSUE THREAD

**Issue by gfwfuckoff** [panda-mute/iptv#1]
在cn挂了hk的ip都打不开

**Comment by ghost** [comment]
这一连bbc的源需要从本土英国本连接.

  我没法从翻墙软件连接到这一连bbc的源.

**Comment by panda-mute** [comment]
对，需要英国IP

**Comment by panda-mute** [comment]
#EXTINF:-1 tvg-logo="http://static.iptv-epg.com/gb/BBCNews.uk.png" group-title="News",BBC News
http://51.52.156.22:8888/http/004
#EXTINF:-1 tvg-logo="http://static.iptv-epg.com/gb/BBCWorldNews.uk.png" group-title="News",BBC World News
http://173.212.237.70/zee5.php?url=http://z5ams.akamaized.net/bbcworldnews/index.m3u8
